#Name of the GitHub Action
name: Workflow-CI-Demo

#Set the action on which the workflow will trigger
on:
  push:
    branches:
      - main

  steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!