#Name of the GitHub Action
name: Workflow-CI-Demo

#Set the action on which the workflow will trigger
on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@master
        run: echo Hello, world!