#Name of the GitHub Action
name: Workflow-CI-Demo

#Set the action on which the workflow will trigger
on: [push,workflow_dispatch]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run the POSTMAN collection
      - name: Run Rick&Morty API tests
        run: newman run https://www.getpostman.com/collections/ba47e81be11dcbfcaae0 -r htmlextra,cli
      - name: Run Google Books API tests
        run: newman run https://www.getpostman.com/collections/b592dc215f4d94952e0f -r htmlextra,cli

      # Upload the contents of Test Results directory to workspace
      - name: Publier le rapport HTML
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report-${{ github.run_id }}
          path: newman/*.html